! This module is used for obtaining time step dynamically
!
  MODULE dynamic_dt
  
  USE mpi
  USE parameters, ONLY: DP,CFL,DT_MAX,NX,NY,NZ,DT,MYID,IERR,SCREEN_LEVEL, &
                        ITURBINE,RADIUS_TURBINE,ROT_SPEED_TURBINE,TOTAL_CELL
  USE class_shared

  CONTAINS
!****************************************************!
!     GENERATE DT DYNAMICALLY                        !
!****************************************************!
    SUBROUTINE GENDT()

    IMPLICIT NONE

    REAL(KIND=DP) :: DX,DY,DZ,MIND,MINDR,MAXU,MAXUR
    REAL(KIND=DP) :: DT_WT

    INTEGER :: I,J,K

    MIND=1.0E10
    MAXU=0.0    
    DO M=1,TOTAL_CELL 
      MIND=MIN(CELL_FV(M)%CELL_DX,MIND)
      MIND=MIN(CELL_FV(M)%CELL_DY,MIND)
      MIND=MIN(CELL_FV(M)%CELL_DZ,MIND)

      MAXU=DMAX1(ABS(CELL_FV(M)%CELL_VAR(1)),MAXU)
      MAXU=DMAX1(ABS(CELL_FV(M)%CELL_VAR(2)),MAXU)
      MAXU=DMAX1(ABS(CELL_FV(M)%CELL_VAR(3)),MAXU)      
    END DO  

    CALL MPI_ALLREDUCE(MIND,MINDR,1,MPI_DOUBLE_PRECISION,MPI_MIN, &
                       MPI_COMM_WORLD,IERR)

    CALL MPI_ALLREDUCE(MAXU,MAXUR,1,MPI_DOUBLE_PRECISION,MPI_MAX, &
                       MPI_COMM_WORLD,IERR)

!---LIMITATION BY CFL NUMBER
    DT=MINDR/MAXUR*CFL
!---LIMITATION BY PRESCRIBED MAXIMUM VALUE
    DT=DMIN1(DT,DT_MAX)
!---LIMITATION BY THE MOTION OF WIND TURBINE 
    IF(ITURBINE.EQ.1)THEN
      DT_WT=MINDR/(ROT_SPEED_TURBINE*RADIUS_TURBINE)
      DT=DMIN1(DT,DT_WT)
    END IF

    END SUBROUTINE

  END MODULE
