! This module is used to declare global arrays
!
  MODULE field_shared

  USE parameters, ONLY: DP

  REAL(KIND=DP),DIMENSION(:),    ALLOCATABLE:: X,Y,Z,XI,YI,ZI
!-VELOCITY FIELD  
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: U0,V0,W0                             
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: U,V,W
!-STRESS FIELD
! STRAIN RATE TENSOR, STRESS TENSOR AND STRESS FORCE

!-FORCE FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: BFX,BFY,BFZ
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: FX,FY,FZ
!-SCALAR FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PD,RHO,MU,TE,TT
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PHI
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: Q1,Q2,Q3 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: TE0      
  REAL(KIND=DP),DIMENSION(:,:),ALLOCATABLE:: Q1W_1,Q1W_2,Q2W_3,Q2W_4,Q3W_5,Q3W_6                                                
!-SGS FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: CS2,BETA,DISSIP,PLM,PMM,PQN,PNN
!-TIME AVERAGED 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PLMA,PMMA,PQNA,PNNA,CS2A,BETAA,NUA,DISA 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UA,VA,WA,TEA,PDA,RHOA
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UTPA,VTPA,WTPA,UPPA,WPPA,VPPA
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: TAU11A,TAU22A,TAU33A,TAU12A,TAU13A,TAU23A
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UUA,VVA,WWA,UVA,UWA,VWA,UTA,VTA,WTA,UPA,VPA,WPA
!-FOR DEBUGGING
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE::CHECK,CHECK0    
 
  END MODULE field_shared
