! This module is used to declare global arrays
!
  MODULE field_shared

  USE parameters, ONLY: DP

  REAL(KIND=DP),DIMENSION(:),    ALLOCATABLE:: X,Y,Z,XI,YI,ZI
!-VELOCITY FIELD  
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: U0,V0,W0                             
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: U,V,W
!-STRESS FIELD
! STRAIN RATE TENSOR, STRESS TENSOR AND STRESS FORCE
!-SCALAR FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PD,RHO,MU,TE
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PHI
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: Q1,Q2,Q3 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: TE0                                                  
 
 
  END MODULE field_shared
