! This module is used to declare global arrays
!
  MODULE field_shared

  USE parameters, ONLY: DP

  REAL(KIND=DP),DIMENSION(:),    ALLOCATABLE:: X,Y,Z,XI,YI,ZI
!-VELOCITY FIELD  
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: U0,V0,W0                             
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UT,VT,WT,U,V,W,UC,VC,WC,UF,VF,WF  
!-STRESS FIELD
! STRAIN RATE TENSOR, STRESS TENSOR AND STRESS FORCE
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: S11,S22,S33,S12,S13,S23,S12C,S13C,S23C,S
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: TAU11,TAU22,TAU33,TAU12,TAU13,TAU23
  REAL(KIND=DP),DIMENSION(:,:),ALLOCATABLE:: TAU12W_1,TAU13W_1,TAU12W_2,TAU13W_2, &
                                             TAU12W_3,TAU23W_3,TAU12W_4,TAU23W_4, &
                                             TAU13W_5,TAU23W_5,TAU13W_6,TAU23W_6
!-FORCE FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: BFX,BFY,BFZ
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: FX,FY,FZ
!-SCALAR FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PD,RHO,MU,TE,TT
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PHI
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: Q1,Q2,Q3 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: TE0      
  REAL(KIND=DP),DIMENSION(:,:),ALLOCATABLE:: Q1W_1,Q1W_2,Q2W_3,Q2W_4,Q3W_5,Q3W_6                                                
!-SGS FIELD
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: NU,CS2,BETA,DISSIP,PLM,PMM,PQN,PNN
!-TIME AVERAGED 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: PLMA,PMMA,PQNA,PNNA,CS2A,BETAA,NUA,DISA 
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UA,VA,WA,TEA,PDA,RHOA
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UTPA,VTPA,WTPA,UPPA,WPPA,VPPA
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: TAU11A,TAU22A,TAU33A,TAU12A,TAU13A,TAU23A
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE:: UUA,VVA,WWA,UVA,UWA,VWA,UTA,VTA,WTA,UPA,VPA,WPA
!-FOR DEBUGGING
  REAL(KIND=DP),DIMENSION(:,:,:),ALLOCATABLE::CHECK,CHECK0    
 
  END MODULE field_shared
