! This module declares the global parameters.
!
  MODULE parameters

  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(14)
! DEFINED IN "parameter.in"
  REAL(KIND=DP) :: LX,LY,LZ,RHO0,MU0,LATITUDE,TR,USTAR0,UG0,VG0,WG0, &
          G,KAPPA,PI,OMEGA_EARTH
! DEFINED IN "solver.in"
  INTEGER :: IINCOM,ITYPE,ISCHEME,ICOLL
  INTEGER :: IFLUX,ILIMIT,ORDER_CON 
  INTEGER :: ITDER,ORDER_TIM
  REAL(KIND=DP) :: CFL,DT_MAX
  REAL(KIND=DP) :: BLEND_CON 
  INTEGER :: IIBM,ITURBINE,ICORI,IGEOB,IBOUS     
  INTEGER :: ORDER_POI,ISCHE_POI,NMUL_POI,NITE_POI  
  REAL(KIND=DP) :: TOLE_POI   
  INTEGER :: ISCALAR,ITEMP
! EDFINED IN "control.in"
  INTEGER :: ISTOP,IRESTART,IPROLX,IPROLY,IPROLZ
  INTEGER :: NXT,NYT,NZT,NPX,NPY,NPZ,NT,SCREEN_LEVEL
  REAL(KIND=DP) :: TIME_MAX
! DEFINED IN "boundary.in" 
  INTEGER :: NBX,NBY,NBZ
  INTEGER :: BC(6,5),IWALL(6)
  REAL(KIND=DP) :: BV(6,5),QS(6),Z0(6)
! DEFINED IN "sgs.in"
  INTEGER :: ISGS,IFILTER,N_SGS_SKIP
  REAL(KIND=DP) :: CS0
! DEFINED IN THE PROCESS
  INTEGER :: N,NSTART,NAVE,I_END
  INTEGER :: NX,NY,NZ
  INTEGER :: NX1,NX2,NY1,NY2,NZ1,NZ2          
  INTEGER :: IERR
  INTEGER :: MYID,MYIDX,MYIDY,MYIDZ       ! INDEX OF EACH SUBDOMAIN
  INTEGER :: LAG_START                    ! TIME STEP WHEN THE LAGRANGIAN SGS MODEL STARTS
  REAL(KIND=DP) :: DX0,DY0,DZ0            ! BASIC GRID SPACING
  REAL(KIND=DP) :: TIME                   ! PHYSICAL TIME
  REAL(KIND=DP) :: DT                     ! TIME STEP
  REAL(KIND=DP) :: UG,VG,WG               ! GEOSTRAPHIC WIND SPEEDS

  REAL(KIND=DP) :: RADIUS_TURBINE         ! MAXIMUM RADIUS OF WIND TURBINE ROTORS
  REAL(KIND=DP) :: ROT_SPEED_TURBINE      ! MAXIMUM ROTATIONAL SPEED OF WIND TURBINES
! FOR GRID EMBEDDING
  INTEGER:: IEMBED  
  INTEGER:: TOTAL_CELL
  INTEGER:: NUM_CELL_LIMIT
  INTEGER:: NUM_VAR
  INTEGER:: TOTAL_CELL_ACTIVE
  INTEGER:: GLOBAL_CELL_ACTIVE
  
  END MODULE parameters
